name: Sync Files with S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region us-east-1  # Update with your region if needed
      - name: Sync files with S3
        run: |
          aws s3 sync source/ s3://${{ secrets.AWS_S3_BUCKET }}/Resume_Design --acl public-read --delete --follow-symlinks
