- name: Sync files with S3
  run: |
    aws s3 sync 'Resume Design/' s3://${{ secrets.AWS_S3_BUCKET }}/Resume_Design --acl public-read --delete --follow-symlinks
  env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_DEFAULT_REGION: us-east-1
